### ISSUE TITLE
Externe Links ebenfalls separat behandeln

### ISSUE THREAD

**Issue by kamulos** [RomanSixty/greasemonkey-spiegelplus#2]
Externe Links "a.text-link-ext" werden derzeit noch rotiert obwohl sie im Klartext vorliegen.

Beispielsweise sichtbar auf der Seite www.spiegel.de/gesundheit/schwangerschaft/durchschlafen-fuer-babys-welche-methode-hilft-am-besten-a-1080408.html

**Comment by RomanSixty** [comment]
Gefixt durch f66e731edee5415b764f2ccbff879524eb7ed315
