### ISSUE TITLE
Eingebettete Videos auf der Startseite funktionieren nicht

### ISSUE THREAD

**Issue by kamulos** [RomanSixty/greasemonkey-spiegelplus#3]
Die Videos auf der Startseite, die durch einen Klick direkt an der Stelle des Vorschaubildes gestartet werden können funktionieren mit diesem Skript nicht mehr. Das tritt auch auf, wenn der Quellcode des Skripts komplett gelöscht wird. Die Ursache ist, dass jQuery über die @require Anweisung geladen wird.

Ich weiß nicht wie das gut gelöst werden kann. Eine einfache Möglichkeit um das Problem zu umgehen wäre das Skript auf der Startseite http://www.spiegel.de/ und auf http://www.spiegel.de/video/* (möglicherweise für Firefox nötig) mit einer @exclude Anweisung gar nicht erst auszuführen

**Comment by RomanSixty** [comment]
Gefixt durch 97fc3be66bcfeb887f2a4db24be0563721fcd528
