### ISSUE TITLE
Not working any more

### ISSUE THREAD

**Issue by m-s-g** [RomanSixty/greasemonkey-spiegelplus#4]
I noticed yesterday that it is not working any more, for instance:

http://www.spiegel.de/plus/herten-buergermeister-der-klammsten-gemeinde-deutschlands-a-5fe417b2-415b-4bf2-be2f-6248a462947a

BR, Mathias

**Comment by RomanSixty** [comment]
It's not very surprising they finally changed an insecure algorithm for something a bit more professional. Since the article's content isn't rendered in full text anymore (not even scrambled) there won't be a fix.
